### ISSUE TITLE
新版ralph

### ISSUE THREAD

**Issue by liangfuting** [wshs2345/ralph-test#1]
Hi，版主好：
 新版的ralph汉化，按照你的教程有问题了，错误如下：
不知道，您还有空研究不？
sudo ralphctl sitetree_resync_apps
Sitetrees found in `ralph.admin` app ...
  Processing `ralph_admin` tree ...
    Adding `Data Center` tree item ...
    Adding `All hosts` tree item ...
    Adding `Add dc host` tree item ...
    Adding `{{ original }}` tree item ...
    Adding `DC Visualization` tree item ...
    Adding `Hardware` tree item ...
    Adding `Add data center asset` tree item ...
    Adding `{{ original }}` tree item ...
    Adding `Components` tree item ...
    Adding `Network` tree item ...
    Adding `Security Info` tree item ...
    Adding `SCM info` tree item ...
    Adding `Relations` tree item ...
    Adding `Licences` tree item ...
    Adding `Supports` tree item ...
    Adding `Operations` tree item ...
    Adding `Current transitions` tree item ...
    Adding `Attachments` tree item ...
    Adding `Virtual Servers` tree item ...
    Adding `Add virtual server (vm)` tree item ...
    Adding `{{ original }}` tree item ...
    Adding `Components` tree item ...
    Adding `Network` tree item ...
    Adding `SCM info` tree item ...
    Adding `Security Info` tree item ...
    Adding `Licences` tree item ...
    Adding `Current transitions` tree item ...
    Adding `Clusters` tree item ...
    Adding `Add cluster` tree item ...
    Adding `{{ original }}` tree item ...
    Adding `Licences` tree item ...
    Adding `Data Centers` tree item ...
    Adding `Add data center` tree item ...
    Adding `{{ original }}` tree item ...
    Adding `Racks` tree item ...
    Adding `Add rack` tree item ...
    Adding `{{ original }}` tree item ...
    Adding `Rack Accessories` tree item ...
    Adding `Add rack accessory` tree item ...
    Adding `{{ original }}` tree item ...
    Adding `Accessories` tree item ...
    Adding `Add accessory` tree item ...
    Adding `{{ original }}` tree item ...
    Adding `Databases` tree item ...
    Adding `Add database` tree item ...
    Adding `{{ original }}` tree item ...
    Adding `Disk Shares` tree item ...
    Adding `Add disk share` tree item ...
    Adding `{{ original }}` tree item ...
    Adding `Server Rooms` tree item ...
    Adding `Add server room` tree item ...
    Adding `{{ original }}` tree item ...
    Adding `VIPs` tree item ...
    Adding `Add vip` tree item ...
    Adding `{{ original }}` tree item ...
    Adding `Preboots` tree item ...
    Adding `Add preboot` tree item ...
    Adding `{{ original }}` tree item ...
    Adding `Preboot configuration` tree item ...
    Adding `Add preboot configuration` tree item ...
    Adding `{{ original }}` tree item ...
    Adding `Preboot files` tree item ...
    Adding `Add preboot file` tree item ...
    Adding `{{ original }}` tree item ...
    Adding `Cloud` tree item ...
    Adding `Cloud hosts` tree item ...
    Adding `Add cloud host` tree item ...
    Adding `{{ original }}` tree item ...
    Adding `Network` tree item ...
    Adding `SCM info` tree item ...
    Adding `Security Info` tree item ...
    Adding `Cloud projects` tree item ...
    Adding `Add cloud project` tree item ...
    Adding `{{ original }}` tree item ...
    Adding `Cloud flavors` tree item ...
    Adding `Add cloud flavor` tree item ...
    Adding `{{ original }}` tree item ...
    Adding `Cloud providers` tree item ...
    Adding `Add cloud provider` tree item ...
    Adding `{{ original }}` tree item ...
    Adding `Back Office` tree item ...
    Adding `Hardware` tree item ...
    Adding `Add back office asset` tree item ...
    Adding `{{ original }}` tree item ...
    Adding `Licence` tree item ...
    Adding `Supports` tree item ...
    Adding `Attachments` tree item ...
    Adding `Current transitions` tree item ...
    Adding `SIM Cards` tree item ...
    Adding `Add sim card` tree item ...
    Adding `{{ original }}` tree item ...
    Adding `Networks` tree item ...
    Adding `Networks` tree item ...
    Adding `Add network` tree item ...
    Adding `{{ original }}` tree item ...
    Adding `Network environments` tree item ...
    Adding `Add network environment` tree item ...
    Adding `{{ original }}` tree item ...
    Adding `Network kind` tree item ...
    Adding `Add network kind` tree item ...
    Adding `{{ original }}` tree item ...
    Adding `IP Addresses` tree item ...
    Adding `Add ip 地址` tree item ...
Traceback (most recent call last):
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1366, "Incorrect string value: '\\xE5\\x9C\\xB0\\xE5\\x9D\\x80' for column 'title' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/ralph/ralph-core/bin/ralph", line 11, in <module>
    sys.exit(prod())
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/__main__.py", line 29, in prod
    main('ralph.settings.prod')
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/__main__.py", line 14, in main
    execute_from_command_line(sys.argv)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/sitetree/management/commands/sitetree_resync_apps.py", line 63, in handle
    item.save(using=using)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/sitetree/models.py", line 141, in save
    super(TreeItemBase, self).save(force_insert, force_update, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1366, "Incorrect string value: '\\xE5\\x9C\\xB0\\xE5\\x9D\\x80' for column 'title' at row 1")

**Comment by CaltropL** [comment]
在数据库里使用命令看一下你的字符集编码是不是utf8mb4
SHOW VARIABLES LIKE 'character_set_database';
字符集编码是latin1的话是无法储存中文的
